### ISSUE TITLE
typographical error in example

### ISSUE THREAD

**Issue by wendellwt** [MobilityDB/PyMEOS#19]
In the Sample Code on the introduction page there is this:
`speed = sequence_from_points.speed()`
and I think it should be this:
`speed = sequence_from_points.speed`

**Comment by Diviloper** [comment]
Hi @wendellwt, in previous versions, many methods (such as `speed`) were annotated as properties. However, this was removed in newer versions, to avoid making the user think that calling the method is "free" (i.e. just getting a member), when in fact it is calling a MEOS function.
It is possible that there is a mismatch in the master branch between the readme and the actual code, but once the new version is moved to master it will be fixed.
