### ISSUE TITLE
TGeomPointSeq and TGeogPointSeq

### ISSUE THREAD

**Issue by mandaawad-connected** [MobilityDB/PyMEOS#24]
Hello team, 
why the method (at) like in the following line doesn't work when the trip type is TGeogPointSeq, what is the alternative?

brussels_inout_trajectories['inside'] = brussels_inout_trajectories['trip'].apply(lambda tr: tr.at(brussels_geom))

**Comment by Diviloper** [comment]
Hi! Does it show any error message? Or the kernel just crashes?
I assume you are trying the BerlinMOD example, amb I right? If that's the case, just know that it has not been updated yet to the last changes in PyMEOS, but it will probably be updated within the next few days.

**Comment by estebanzimanyi** [comment]
Alas, the at functions requires to compute spatial intersection which is provided by GEOS, and GEOS only work with plannar Cartesian coordinates. This limitation also shows in PostGIS (which also uses GEOS in its backend)
https://postgis.net/docs/ST_Intersection.html
which says "Performed by the GEOS module" and the version for geographies they say "For geography this is a thin wrapper around the geometry implementation."

**Comment by mandaawad-connected** [comment]
what is the alternative? what to use? 
I have the trajectory for the trip which is TGeogPointSeq type and the provinces are also in the following type
POLYGON ((35.78606033 32.20119095, 35.78001785 32.19791412, 35.77044296 32.19367981, 35.76490402 32.19005203, 35.75456619 32.18144989, 35.74267197 32.16957474, 35.73338318 32.17431259, 35.72740555 32.17792892, 35.72211838 32.18185806, 35.7139473 32.18916702, 35.70883942 32.19416046, 35.70277405 32.20175552, 35.69780731 32.20584488, 35.69352722 32.21032333, 35.68748474 32.2156868, 35.67780304 32.22881699, 35.66703796 32.2452507,  35.82796478 32.40106583, 35.8352356 32.40587234, 35.84075546 32.40420151, 35.84944916 32.4008522, 35.85922623 32.3989563, 35.87224197 32.39762115, 35.8848381 32.39906311, 35.88931274 32.39999008, 35.89334869 32.40148544, 32.31770706, 35.88522339 32.31555176, 35.88333893 32.31414032, 35.88010025 32.31087112, 35.8778038 32.30703735, 35.87398911 32.29470444, 35.86927795 32.28488922, 35.86804962 32.28039169, 35.86550522 32.26418304, 35.86388779 32.25994492, 35.85990143 32.25224304, 35.85662079 32.24251938, 35.85473633 32.23918915, 35.84593201 32.23044968, 35.84075928 32.22677231, 35.83723068 32.22360611, 35.83439636 32.22161865, 35.82092285 32.21492767, 35.8106041 32.21094513, 35.80503082 32.20840454, 35.79948425 32.20598984, 35.78606033 32.20119095))

What function should I use to get the trips inside and outside specific provinces?

**Comment by estebanzimanyi** [comment]
You would need to convert the data into a planar coordinate system using one of the standard SRIDs as reported in https://epsg.io/.

**Comment by mandaawad-connected** [comment]
there isn't a builtin function in pymeos that does this conversion because I tried to convert the tGeogPointSeq to TGeomPointSeq but it didn't work, the kernel crashes!

**Comment by estebanzimanyi** [comment]
We can look into this issue but we need to have more information about the input data to be able to reproduce it.
In the meantime you can do this transformation on the INPUT data BEFORE importing the data in PyMEOS.

**Comment by mandaawad-connected** [comment]
it's a realtime data, how please we convert the point from geodetic to cartesian planar using pymeos?

**Comment by estebanzimanyi** [comment]
You need to understand which planar SRID you should use for the geo location of your real-time data. And then you can use shapely, pyproj or other standard library for transforming the coordinates BEFORE sending the temporal data to PyMEOS

**Comment by Diviloper** [comment]
As @estebanzimanyi mentioned, you need to find a suitable SRID for your data. Once you have it, you can easily change projections using [pyproj](https://pyproj4.github.io/pyproj/stable/api/transformer.html). You can see an example of this process in the [ACM Singapore demo](https://github.com/Diviloper/PyMEOS-demo/blob/main/ACM-Singapore/PyMEOS-ACM.ipynb) (5th cell).
In it, we have a pandas DataFrame with point in [EPSG:4326](https://epsg.io/4326), and convert them to [EPSG:3414](https://epsg.io/3414) (which covers the area of Singapore) before creating the TGeomSeq objects.
