### ISSUE TITLE
using srid=None result in Segmentation fault

### ISSUE THREAD

**Issue by DeoLeung** [MobilityDB/PyMEOS#60]
**Describe the bug**
```python
TGeogPointInst(point=(0,0,0), timestamp=datetime.now(), srid=None)
# Segmentation fault: 11
```

**To Reproduce**
run the above code

**Expected behavior**
want to test using sensor data which without geospatial reference system

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macos
- Architecture: m1
- Environment: pip
 - Version
 pymeos                                   1.1.3
pymeos_cffi                              1.1.1

**Comment by Diviloper** [comment]
This issue (along with #61) has been fixed and a new [pymeos version (1.1.4)](https://pypi.org/project/pymeos/1.1.4/) has been released.
Many thanks for bringing this up!
