### ISSUE TITLE
Errors in Readme

### ISSUE THREAD

**Issue by anitagraser** [MobilityDB/PyMEOS#7]
The example from the Readme fails with

```
>>> meos_initialize()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: meos_initialize() missing 1 required positional argument: 'tz_str'
```

**Comment by Diviloper** [comment]
Hi @anitagraser,
You can find an updated version of the README in the [develop branch](https://github.com/MobilityDB/PyMEOS/tree/develop).
The code there should be working fine.

**Comment by anitagraser** [comment]
```
>>> sequence_from_points = TGeogPointSeq(instant_list=[TGeogPointInst(string='Point(10.0 10.0)@2019-09-01 00:00:00+01'), TGeogPointInst(string='Point(20.0 20.0)@2019-09-02 00:00:00+01'), TGeogPointInst(string='Point(10.0 10.0)@2019-09-03 00:00:00+01')], lower_inc=True, upper_inc=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/agraser/.local/lib/python3.8/site-packages/pymeos/main/tpoint.py", line 847, in __init__
    super().__init__(string=string, instant_list=instant_list, lower_inc=lower_inc, upper_inc=upper_inc,
  File "/home/agraser/.local/lib/python3.8/site-packages/pymeos/temporal/tsequence.py", line 61, in __init__
    self._inner = tsequence_make(self._instants, len(self._instants), len(self._instants), lower_inc, upper_inc,
TypeError: tsequence_make() takes 6 positional arguments but 7 were given
```

**Comment by Diviloper** [comment]
Hi @anitagraser, could you provide the version number for pymeos and pymeos_cffi?

**Comment by anitagraser** [comment]
I just pip installed today:

```
Collecting pymeos
  Downloading pymeos-1.1.1-py3-none-any.whl (60 kB)
...
Collecting pymeos-cffi==0.0.18
  Downloading pymeos_cffi-0.0.18-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (7.7 MB)
```

Is there a pymeos function to show the version? pymeos.__version__() doesn't seem to exist.

**Comment by Diviloper** [comment]
There is no built-in way to get the version, although I'll look into adding it for the next version.
I looked into it and the uploaded `pymeos` package didn't contain every commit it should have. I've uploaded a patch (1.1.1-post1) that should fix it.
It's working fine in a clean project I've created to test it, but can you update it (`pip install --upgrade pymeos`) and run it again to confirm it?

**Comment by anitagraser** [comment]
Thank you, Víctor. The Readme code now works with 1.1.1-post1.
